### ISSUE TITLE
视频滑动灵敏度优化

### ISSUE THREAD

**Issue by ShaoNian-end** [xlist-io/xlist#17]
希望可以手动调整滑动灵敏度，感觉现在灵敏度有些高，稍微一滑偏离太多

**Comment by cdoco** [comment]
+1 我会在下个版本降低一点滑动灵敏度, 但是可能在近期不会提供用户可选择的灵敏度级别。

**Comment by ShaoNian-end** [comment]
> +1 我会在下个版本降低一点滑动灵敏度, 但是可能在近期不会提供用户可选择的灵敏度级别。

感谢
