### ISSUE TITLE
enhance of both alist and client

### ISSUE THREAD

**Issue by seanhe26** [xlist-io/xlist#22]
hi,

I think your project is very promising. so im wondering if you will make it open soure?
I'm recently enhanching alist, below is the feature I want to impletment:
1. client direct acess remote storage url with header returned by alist server(many of storage provider need special header, etc.) so people don't need alist-proxy to proxy the data, also client will have max speed
2. implement transparent encryption & decrytion function, again, user will acces the file securely with good performance.

if you decide to open source this client project, I will implement those features. let me know what you think. thanks.

**Comment by cdoco** [comment]
This project will not be open source at this stage, we may consider releasing an open source version after a while.
