### ISSUE TITLE
iOS端的搜索功能似乎用不了，输入内容点确认后没有反应。

### ISSUE THREAD

**Issue by AssassinHjx** [xlist-io/xlist#27]
iOS端的搜索功能似乎用不了，输入内容点确认后没有反应。

**Comment by cdoco** [comment]
你可以检测一下在 alist 服务上是否能够使用搜索功能。

**Comment by AssassinHjx** [comment]
> 

哦，抱歉我发现是我的alist数据库出现了问题。重建后好了。谢谢

**Comment by PinkyJie** [comment]
我在安卓上也碰到了无法搜索的问题，但在alist的网页上是可以搜索的，这个有什么办法排查吗？
