### ISSUE TITLE
iis配置反代https无法连接

### ISSUE THREAD

**Issue by AssassinHjx** [xlist-io/xlist#29]
我的alist部署在win10pro 22h2系统上再使用iis配置反代，证书使用dnspod的免费证书。网页登陆正常，在xlist中添加服务器时提升出错（如图）
![IMG_0427](https://github.com/xlist-io/xlist/assets/91854457/048ace69-2a6d-4d9f-bf95-3c8542469dcc)

**Comment by cdoco** [comment]
TLS renegotiation 默认是被禁止的, 因为开启这个可能会导致对 HTTPS 会话实施中间人注入攻击, 我后续会评估一下是否对这种情况提供支持。
