### ISSUE TITLE
iOS，Android重复付费问题

### ISSUE THREAD

**Issue by erbanku** [xlist-io/xlist#38]
如题，能否支持一次支付即可在iOS和Android上共享权益

**Comment by cdoco** [comment]
目前 Xlist 是本地应用, 没有可以同步的账号系统, 如果全端同步权益的话就需要登录账号, 这个还需要评估一下。

**Comment by erbanku** [comment]
其实我也反对加账号系统。或许可以考虑别的办法，比如在购买时生成激活码，用这个激活码来激活其他设备（可以限制激活设备的数量等）。

**Comment by cdoco** [comment]
IOS 虚拟商品只允许使用内购支付, 激活码这个可能行不通。
